"""
@Description :   Recorded high-frequency medical words in various languages, which are generated by ChatGPT.
@Author      :   Henrychur 
@Time        :   2023/10/11 09:46:35
"""
fr_medical_biology_words = [
    "Cellule", "ADN", "ARN", "Gène", "Protéine", "Chromosome", "Mutation", "Genome",
    "Transcription", "Traduction", "Réplication", "Mitose", "Méiose", "Organisme", "Système",
    "Organe", "Tissu", "Cellule souche", "Microscope", "Noyau", "Cytoplasme", "Membrane cellulaire",
    "Organite", "Mitochondrie", "Ribosome", "Endoplasmic reticulum", "Appareil de Golgi", "Lysosome",
    "Cycle cellulaire", "Apoptose", "ADN polymérase", "RNA polymérase", "Enzyme", "Acide aminé",
    "Récepteur", "Ligand", "Hormone", "Antigène", "Immunologie", "Anticorps", "Vaccin", "Allergie",
    "Inflammation", "Microbe", "Bactérie", "Virus", "Parasite", "Prion", "Pathogène", "Immunité",
    "Système immunitaire", "Leucocyte", "Phagocyte", "Lymphocyte", "Lymphatique", "Immunoglobuline",
    "T-cellule", "B-cellule", "Antigène HLA", "Réaction immunitaire", "SIDA", "Cancer", "Tumeur",
    "Métastase", "Carcinome", "Biopsie", "Radiographie", "IRM", "Scanner", "Chirurgie", "Anesthésie",
    "Greffe", "Transplantation", "Organisme génétiquement modifié", "Clonage", "Thérapie génique",
    "Séquençage", "Génétique des populations", "Évolution", "Hérédité", "Maladie génétique", "Décès",
    "Symptôme", "Diagnostic", "Traitement", "Médicament", "Thérapie", "Prévention", "Rééducation",
    "Physiothérapie", "Nutrition", "Alimentation", "Métabolisme", "Diabète", "Obésité", "Cholestérol",
    "Hypertension", "Maladie cardiovasculaire", "Respiration", "Circulation sanguine"
]

fr_medical_words = [
    "Médecine", "Santé", "Maladie", "Patient", "Docteur", "Hôpital", "Soins", "Diagnostic",
    "Traitement", "Médicament", "Chirurgie", "Infirmière", "Pharmacie", "Consultation", "Prescription",
    "Symptôme", "Fièvre", "Douleur", "Blessure", "Soin de santé", "Prévention", "Vaccination", "Virus",
    "Bactérie", "Infection", "Immunité", "Immunisation", "Greffe", "Transplantation", "Rétablissement",
    "Réadaptation", "Radiographie", "IRM", "Scanner", "Laboratoire", "Test", "Efficacité",
    "Effets secondaires", "Pharmacologie", "Réanimation", "Urgence", "Ambulance", "Anesthésie",
    "Opération", "Anesthésiste", "Cardiologie", "Neurologie", "Gynécologie", "Pédiatrie", "Psychiatrie",
    "Oncologie", "Dermatologie", "Radiologie", "Orthopédie", "Stéthoscope", "Tension artérielle",
    "Fréquence cardiaque", "Pouls", "Respiration", "Mal de tête", "Nausée", "Fatigue", "Stress",
    "Dépression", "Allergie", "Diabète", "Obésité", "Cholestérol", "Hypertension", "Asthme", "Arthrite",
    "Cancer", "Sida", "Maladie cardiaque", "Accident vasculaire cérébral", "Douleur chronique",
    "Rééducation", "Physiothérapie", "Nutrition", "Alimentation", "Exercice", "Santé mentale",
    "Hygiène", "Prévention des maladies", "Système de soins de santé", "Assurance santé",
    "Médecine alternative", "Médecine complémentaire", "Médecine préventive", "Recherche médicale",
    "Essai clinique", "Système immunitaire", "Système digestif", "Système respiratoire", "Système cardiovasculaire",
    "Système nerveux", "Système endocrinien", "Système musculo-squelettique", "Système reproducteur",
    "Système lymphatique"
]

zh_medical_biology_words = [
    "医学", "生物学", "细胞", "基因", "疾病", "诊断", "治疗", "疫苗", "病毒", "细菌",
    "遗传", "免疫系统", "病理学", "组织", "器官", "肿瘤", "蛋白质", "血液", "心脏", "肺",
    "肝脏", "肾脏", "大脑", "神经系统", "克隆", "遗传工程", "药物", "毒素", "细胞周期",
    "免疫反应", "细菌感染", "疫情", "病毒传播", "肿瘤治疗", "细胞分裂", "遗传疾病", "基因编辑",
    "遗传变异", "细胞死亡", "血压", "病原体", "免疫疫苗", "妊娠", "遗传密码", "增殖",
    "遗传性疾病", "器官移植", "胰岛素", "遗传多样性", "病理病变", "免疫抗体", "蛋白合成", "血型",
    "遗传咨询", "细胞膜", "心血管系统", "肺疾病", "肝炎", "肾功能", "大脑疾病", "神经元",
    "细胞核", "遗传修复", "药理学", "毒物学", "免疫抵抗", "细菌耐药性", "疫苗接种", "免疫缺陷",
    "疾病预防", "遗传突变", "细胞生长", "病原微生物", "内分泌系统", "遗传变体", "脑神经病",
    "细胞分化", "遗传标志物", "药物代谢", "细胞遗传学", "遗传表达", "肺功能测试", "免疫细胞",
    "细胞信号传导", "遗传遗传", "免疫疾病", "细胞增殖", "疫苗研究", "遗传学家", "药物剂量",
    "细胞生物学", "重大疫情", "遗传突变体", "病原体识别", "免疫抗原", "细胞核酸", "遗传多态性",
    "毒物暴露", "免疫耐受性", "遗传病筛查"
]

zh_medical_words = [
    "医学", "医生", "病人", "医院", "药物", "治疗", "诊断", "疾病", "手术", "症状",
    "护士", "健康", "疼痛", "药方", "疫苗", "患者", "药店", "预防", "检查", "病情",
    "麻醉", "诊所", "处方", "血压", "病原体", "化验", "肿瘤", "免疫系统", "治疗方案", "全身检查",
    "病历", "传染病", "病毒", "细菌", "疾病预防", "看诊", "咨询医生", "医学研究", "临床试验", "心脏病",
    "肺病", "癌症", "糖尿病", "神经系统疾病", "心血管疾病", "药物副作用", "急救", "免疫接种", "外科手术", "内科医生",
    "肿瘤治疗", "妇科", "儿科", "医学专家", "家庭医生", "骨折", "呼吸道感染", "胃炎", "肠胃疾病", "看病费用",
    "眼科", "耳鼻喉科", "接受手术", "器官移植", "药物治疗", "胃溃疡", "中药", "牙科医生", "放射治疗", "血液检查",
    "肌肉疾病", "肾脏疾病", "精神疾病", "神经病", "治疗计划", "康复", "疼痛管理", "病原微生物", "免疫抵抗力", "病原体识别",
    "营养", "医学教育", "卫生保健", "基因疗法", "健康保险", "临床医学", "生殖健康", "睡眠障碍", "皮肤科", "诊断仪器",
    "疫情控制", "预防接种", "抗生素", "病人护理", "健康检查", "药物滥用", "公共卫生", "遗传研究", "心脏手术", "疫苗疫苗"
]

sp_medical_biology_words = [
    "Biología", "Médico", "Célula", "Gen", "ADN", "ARN", "Proteína", "Enzima", "Virus", "Bacteria",
    "Microorganismo", "Organismo", "Evolución", "Herencia", "Mutación", "Replicación", "Transcripción",
    "Traducción", "Genoma", "Cromosoma", "Mutante", "Clonación", "Genética", "Genotipo", "Fenotipo",
    "Genoma humano", "Hereditario", "Mutagénesis", "Genómica", "Secuenciación", "Regulación", "Expresión",
    "Transgénico", "Terapia génica", "Reproducción", "Fertilización", "Embrión", "Cigoto", "Feto",
    "Genes homeóticos", "Genotipado", "Epigenética", "Cromatina", "Citoplasma", "Membrana celular",
    "Núcleo", "Mitocondria", "Ribosoma", "Organelo", "Tejido", "Órgano", "Sistema", "Aparato",
    "Organismo multicelular", "Tejido conectivo", "Tejido muscular", "Tejido nervioso", "Tejido epitelial",
    "Tejido adiposo", "Tejido óseo", "Tejido cartilaginoso", "Sangre", "Sistema circulatorio", "Sistema respiratorio",
    "Sistema digestivo", "Sistema excretor", "Sistema endocrino", "Sistema nervioso", "Sistema inmunológico",
    "Sistema linfático", "Sistema reproductor", "Glándula", "Hormona", "Metabolismo", "Homeostasis",
    "Sistema de defensa", "Sistema linfático", "Sistema cardiovascular", "Sistema muscular", "Sistema esquelético",
    "Sistema tegumentario", "Sistema urinario", "Sistema endocrino", "Sistema nervioso central",
    "Sistema nervioso periférico", "Sistema inmunológico", "Sistema reproductor masculino", "Sistema reproductor femenino",
    "Genotipo", "Fenotipo", "Genoma", "Genómica", "Transcripción", "Traducción", "Regulación génica", "Expresión génica",
    "Mutación", "Replicación del ADN", "Mutágeno", "ADN recombinante"
]

sp_medical_words = [
    "Medicina", "Paciente", "Enfermedad", "Diagnóstico", "Tratamiento", "Cirugía", "Hospital", "Doctor", "Enfermera", "Farmacia",
    "Receta", "Síntoma", "Terapia", "Medicamento", "Cuidado", "Salud", "Lesión", "Consulta", "Especialista", "Radiografía",
    "Análisis", "Laboratorio", "Epidemia", "Virus", "Bacteria", "Infección", "Inmunización", "Vacuna", "Prevención", "Rehabilitación",
    "Fisioterapia", "Psicoterapia", "Nutrición", "Dietista", "Obesidad", "Cardiología", "Neumología", "Oncología", "Pediatría", "Ginecología",
    "Dermatología", "Psiquiatría", "Urología", "Oftalmología", "Otorrinolaringología", "Endocrinología", "Neurología", "Radiología", "Gastroenterología",
    "Hematología", "Nefrología", "Cardiólogo", "Neumólogo", "Oncólogo", "Pediatra", "Ginecólogo", "Dermatólogo", "Psiquiatra", "Urólogo",
    "Oftalmólogo", "Otorrinolaringólogo", "Endocrinólogo", "Neurocirugía", "Radiólogo", "Gastroenterólogo", "Hematólogo", "Nefrólogo", "Cirujano", "Anestesia",
    "Urgencias", "Medicina interna", "Medicina de emergencia", "Medicina alternativa", "Medicina complementaria", "Enfermedad crónica", "Enfermedad aguda", "Historia clínica",
    "Diagnóstico por imagen", "Ultrasonido", "Tomografía", "Resonancia magnética", "Enfermedades cardiovasculares", "Enfermedades infecciosas", "Enfermedades autoinmunes",
    "Trasplante de órganos", "Genética médica", "Farmacología", "Antibiótico", "Analgésico", "Antinflamatorio", "Psicofármaco", "Antidepresivo", "Anestésico", "Antiviral",
    "Inmunosupresor", "Hipertensión", "Diabetes", "Artritis", "Alzheimer", "Parkinson"
]

ru_medical_biology_words = [
    "Биология", "Медицина", "Генетика", "Молекула", "Клетка", "Организм", "ДНК", "Ген", "Геном", "РНК", "Белок",
    "Вирус", "Эволюция", "Антибиотик", "Бактерия", "Вакцина", "Иммунитет", "Заразный", "Гормон", "Диагноз", "Лекарство",
    "Операция", "Рак", "Сердце", "Мозг", "Печень", "Почка", "Легкие", "Кровь", "Кость", "Желудок", "Кожа", "Сосуд",
    "Аллергия", "Воспаление", "Аутоиммунный", "Мутация", "Гипотеза", "Патология", "Генетический", "Медицинский", "Лечение",
    "Орган", "Симптом", "Анализ", "Клонирование", "Биотехнология", "Генная терапия", "Геномика", "Биохимия",
    "Микробиология", "Генотип", "Фенотип", "Протозоа", "Внутренний", "Внешний", "Размножение", "Метаболизм", "Экспрессия",
    "Инфекция", "Генерация", "Адаптация", "Транскрипция", "Трансляция", "Синтез", "Мутаген", "Вирулентность",
    "Профилактика", "Лечебный", "Эпидемия", "Микроорганизм", "Иммунология", "Клеточный цикл", "Антитело",
    "Медицинская генетика", "Фермент", "Генетический код", "Онкология", "Трансплантация", "Сперма", "Овуляция",
    "Коагуляция", "Биологический вид", "Субклеточная структура", "Гипоталамус", "Анемия", "Эндокринология",
    "Красная кровь", "Органелла", "Митоз", "Мейоз", "Нейрон", "Гипофиз", "Тиреоид", "Гастроэнтерология", "Хромосома",
    "Лимфоцит", "Бактериофаг", "Простата", "Рецептор"
]


ru_medical_words = [
    "Медицина", "Врач", "Пациент", "Лечение", "Больница", "Заболевание", "Симптом", "Диагноз", "Рецепт", "Операция",
    "Сестра", "Аптека", "Здоровье", "Вакцина", "Лекарство", "Анестезия", "Терапия", "Палата", "Хирургия", "Анализ",
    "Рентген", "Экстренная помощь", "Болезнь", "Восстановление", "Стетоскоп", "Специалист", "Уход", "Онкология",
    "Ортопедия", "Гинекология", "Педиатрия", "Сердце", "Легкие", "Печень", "Почки", "Желудок", "Головная боль",
    "Аллергия", "Профилактика", "Иммунитет", "Гормоны", "Биопсия", "Инфекция", "Ожирение", "Диабет", "Кровь",
    "Анемия", "Венозная система", "Артерии", "Гипертония", "Дыхание", "Температура", "Бактерии", "Вирус",
    "Иммунология", "Антибиотики", "Реабилитация", "Психиатрия", "Психотерапия", "Урология", "Офтальмология",
    "Неврология", "Генетика", "Эндокринология", "Остеопатия", "Генетический анализ", "Стоматология", "Аптекарь",
    "Рентгенология", "Иммунизация", "Трансплантация", "Акушерство", "Геномика", "Медицинская история",
    "Биохимия", "Алкоголизм", "Рак", "Хирургический инструментарий", "Генетические болезни", "Генетическая терапия",
    "Реанимация", "Анафилаксия", "Кардиология", "Психология", "Электрокардиограмма", "Рефлексология", "Токсикология",
    "Стоматолог", "Гастроэнтерология", "Фармакология", "Гиппократическая клятва", "Радиология", "Гомеопатия",
    "Акупунктура", "Воспаление", "Атеросклероз", "Остеоартрит", "Артрит", "Туберкулез", "Медицинская этика"
]

jp_medical_biology_words = [
    "医学", "生物学", "細胞", "遺伝子", "疾患", "免疫", "代謝", "病理学", "酵素", "蛋白質", "DNA", "RNA", "細胞核", "細胞膜", 
    "細胞質", "細菌", "ウイルス", "遺伝学", "遺伝子工学", "癌", "微生物学", "免疫学", "ウイルス学", "細胞分裂", "血液", "血液型", 
    "血圧", "血糖", "血管", "心臓", "肺", "肝臓", "腎臓", "脳", "神経", "脊髄", "筋肉", "骨", "皮膚", "免疫系", "免疫反応", 
    "抗生物質", "感染", "病原体", "感染症", "治療", "予防", "診断", "薬物", "副作用", "症状", "病院", "医師", "看護師", 
    "患者", "手術", "研究", "実験", "解剖学", "生理学", "免疫力", "クローン", "遺伝的", "細菌学", "疫学", "遺伝疾患", 
    "遺伝子変異", "白血球", "赤血球", "血小板", "血漿", "免疫システム", "ホルモン", "炎症", "治療法", "免疫抑制", "細胞生物学", 
    "遺伝子解析", "薬理学", "感染制御", "血液検査", "微生物感染", "腫瘍学", "脳神経科学", "遺伝子治療", "病気予防", 
    "先天性疾患", "免疫不全", "細胞診", "細胞増殖", "細胞死", "遺伝子発現", "細胞分子生物学", "免疫療法", "血液凝固", 
    "病原性微生物", "先進医療", "微生物叢", "脳外科学"
]

jp_medical_words = [
    "医学", "医療", "診断", "治療", "病院", "医師", "看護師", "患者", "薬物", "手術", "病気", "疾患", "症状", "診療", "予防", 
    "臨床", "体温", "血圧", "心臓", "肺", "腎臓", "肝臓", "脳", "神経", "眼科", "耳鼻咽喉科", "歯科", "内科", "外科", "小児科", 
    "婦人科", "皮膚科", "精神医学", "放射線", "薬理学", "血液学", "毒性学", "生理学", "病理学", "衛生学", "免疫学", "微生物学", 
    "ウイルス学", "細菌学", "遺伝学", "遺伝子", "ゲノム", "オルガン", "細胞", "細胞核", "細胞膜", "細胞質", "クローン", "遺伝的", 
    "遺伝子工学", "ゲノム編集", "分子生物学", "タンパク質", "酵素", "代謝", "グリコーゲン", "脂質", "タンパク合成", "DNA", "RNA", 
    "細胞分裂", "細胞増殖", "免疫系", "抗体", "免疫反応", "インフルエンザ", "HIV", "白血球", "赤血球", "血小板", "血漿", 
    "血液型", "血液凝固", "血糖", "血液循環", "全身麻酔", "局所麻酔", "鎮痛剤", "抗生物質", "抗炎症薬", "抗がん剤", "胃薬", 
    "鎮静剤", "解熱剤", "疼痛", "癌", "腫瘍", "転移", "化学療法", "放射線療法", "手術室", "看護師", "循環器", "消化器", "呼吸器"
]
